routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('classes','ClassesController');
Route::resource('welcome','PagesController');
Route::get('/','PagesController@index');
Route::get('udelete/{id}','PagesController@destroy');
//Route::get('/destroy/{id}','PagesController@destroy');
Auth::routes();
Route::any('/admin', 'AdminController@index')->name('admin')->middleware('admin');
Route::any('/user', 'UserController@index')->name('user')->middleware('user');
Route::get('/create','ClassesController@create')->name('create');
Route::get('/classlist','ClassesController@index')->name('classlist');
Route::get('/userlist', 'PagesController@userlist')->name('userlist');
Route::any('edit/{id}','ClassesController@edit');
Route::get('delete/{id}','ClassesController@destroy');
//Route::any('destroy/{id}','ClassesController@destroy');
//Route::any('/home', 'HomeController@index')->name('home');
//Route::post('/admin', 'AdminController@index')->name('admin')->middleware('admin');
//Route::get('/user', 'UserController@index')->name('user')->middleware('user');
//Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/ClassesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Classes;
use Auth;
use Framework\Sessions;
use Illuminate\Support\Facades\DB;

class ClassesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(!Auth::check()){
            return 'To see the class list you have to log in first!!';
        }
        $classes = Classes::orderBy('id','desc')->get();
        return view('classes.classlist')->with('classes',$classes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!Auth::check()){
            return redirect()->route('login');
        }
        elseif(Auth::user()->role == 1){
            return view('classes.create');
        }
        else{
            return 'Only teacher can create a class!!';
        }
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required|min:10|max:100',
            'date' => 'required',
            'time' => 'required'
        ]);
        $classes = new Classes;

        $classes->title = $request->title;
        $classes->date = $request->date;
        $classes->time = $request->time;

        $classes->save();

        //passes massege after save
        $request->session()->flash('success', 'The class was successfully posted!');

        //redirect to another page
        return redirect()->route('classes.show', $classes->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
        $classes = Classes::find($id);
        return view('classes.show')->withClasses($classes);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!Auth::check()){
            return redirect()->route('login');
        }
        elseif(Auth::user()->role == 1){
        $classes = Classes::find($id);
        return view('classes.edit')->withClasses($classes);
    }
    else{
        return 'Only a teacher can edit a class!!';
    }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $classes = Classes::find($id);
        $validatedData = $request->validate([
            'title' => 'required|min:10|max:100',
            'date' => 'required',
            'time' => 'required'
        ]);

        $classes->title = $request->title;
        $classes->date = $request->date;
        $classes->time = $request->time;

        $classes->update();

        //passes massege after save
        $request->session()->flash('success', 'The post was successfully updated!');

        //redirect to another page
        return redirect()->route('classes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        if(!Auth::check()){
            return redirect()->route('login');
        }
        elseif(Auth::user()->role == 1){
        DB::delete('delete from classes where id = ?',[$id]);
        $request->session()->flash('success', 'The post was successfully deleted!');
        return redirect()->route('classes.index');  
    }
    else{
        return 'Only a teacher can delete a class!!';
    }
    }
}

resources/views/classes/classlist.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
               <center><strong> <div class="card-header">{{ __('Class List') }}</div></strong></center>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                <table class="table table-hover table-dark">
                  <thead>
                    <tr>
                      <th scope="col">Title</th>
                      <th scope="col">Date</th>
                      <th scope="col">time</th>
                      <th scope="col">Edit</th>
                      <th scope="col">Delete</th>
                    </tr>
                  </thead>
                  <tbody>
                    @if(count($classes) > 0)
                    @foreach ($classes as $classes)
                    <tr>
                      <td scope="row">{{$classes->title}}</td>
                      <td>{{$classes->date}}</td>
                      <td>{{$classes->time}}</td>
                    <td><a class="btn btn-warning" href="{{ route('classes.edit',$classes->id) }}" role="button">Edit</a></td>
                    <td><a class="btn btn-danger" href = 'delete/{{ $classes->id }}'>Delete</a></td></td>
                    </tr>
                    @endforeach
                    @else
                       <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                          {{ __('No Class created yet') }}
                       </h2> 
                    @endif 
                  </tbody>
                </table> 
</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/classes/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
               <center><strong> <div class="card-header">{{ __('Create new Class') }}</div></strong></center>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-header">
        Create a class
      </div>
      <div class="card-body">
      <form method="POST" action="{{route('classes.store')}}">
        @csrf  
        <div class="form-group">
            <label for="title">Class Title</label>
            <input type="text" class="form-control" id="title" name="title">
            @error('title')
               <span class="text-danger">{{$message}}</span> 
            @enderror
          </div>
          <div class="form-group">
            <label for="date">Date</label>
            <input type="date" class="form-control" id="date" name="date">
            @error('date')
            <span class="text-danger">{{$message}}</span> 
         @enderror
          </div>
          <div class="form-group">
            <label for="time">Time</label>
            <input type="time" class="form-control" id="time" name="time">
            @error('time')
            <span class="text-danger">{{$message}}</span> 
         @enderror
          </div>
          <center><button type="submit" class="btn btn-primary">Submit</button></center>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/classes/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
               <center><strong> <div class="card-header">{{ __('Edit/Update Class') }}</div></strong></center>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-header">
        Edit/Update class
      </div>
      <div class="card-body">
      <form method="POST" action="{{route('classes.update',$classes->id)}}">
        @csrf  
        @method('PUT')
        <div class="form-group">
            <label for="title">Class Title</label>
            <input type="text" class="form-control" id="title" name="title">
            @error('title')
               <span class="text-danger">{{$message}}</span> 
            @enderror
          </div>
          <div class="form-group">
            <label for="date">Date</label>
            <input type="date" class="form-control" id="date" name="date">
            @error('date')
            <span class="text-danger">{{$message}}</span> 
         @enderror
          </div>
          <div class="form-group">
            <label for="time">Time</label>
            <input type="time" class="form-control" id="time" name="time">
            @error('time')
            <span class="text-danger">{{$message}}</span> 
         @enderror
          </div>
          <center><button type="submit" class="btn btn-primary">Update class</button></center>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/classes/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
               <center><strong> <div class="card-header">{{ __('Class has been created') }}</div></strong></center>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                <table class="table table-hover table-dark">
                  <thead>
                    <tr>
                      <th scope="col">Title</th>
                      <th scope="col">Date</th>
                      <th scope="col">time</th>
                      <th scope="col">Edit</th>
                      <th scope="col">Delete</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td scope="row">{{$classes->title}}</td>
                      <td>{{$classes->date}}</td>
                      <td>{{$classes->time}}</td>
                      <td><a class="btn btn-warning" href="{{ route('classes.edit',$classes->id) }}" role="button">Edit</a>
                        <td><a class="btn btn-danger" href="{{ route('classes.destroy',$classes->id) }}" role="button">Delete</a>
                    </tr>
                  </tbody>
                </table> 
</div>
</div>
</div>
</div>
</div>
@endsection